# Generated by Django 5.0.1 on 2024-01-03 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=100)),
                ('companyDescription', models.TextField()),
                ('companyIndustry', models.CharField(max_length=50)),
                ('companyLocation', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100)),
                ('userBio', models.CharField(max_length=150)),
                ('userProfilePicture', models.ImageField(upload_to='')),
                ('userPrice', models.IntegerField()),
                ('userSkills', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobTitle', models.CharField(max_length=300)),
                ('jobDescription', models.TextField()),
                ('jobSalary', models.IntegerField()),
                ('jobWorkTime', models.CharField(max_length=50)),
                ('jobType', models.CharField(max_length=50)),
                ('jobSkills', models.TextField()),
                ('jobCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_board.company')),
            ],
        ),
    ]
