# Generated by Django 5.0.1 on 2024-01-05 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0002_company_posted_by_job_posted_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='posted_by',
            new_name='created_by',
        ),
    ]
