# Generated by Django 5.0.1 on 2024-01-05 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0003_rename_posted_by_company_created_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
